# -*- coding: utf-8 -*-
# Generated by Django 1.9.2.dev20160111111649 on 2016-01-12 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20151211_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='period_registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_result', to='period_registrations.PeriodRegistration'),
        ),
    ]
