# -*- coding: utf-8 -*-
# Generated by Django 1.9.3.dev20160206142456 on 2016-02-13 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degrees.Degree'),
        ),
    ]
