# -*- coding: utf-8 -*-
# Generated by Django 1.9.3.dev20160206142456 on 2016-02-14 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20160214_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='degrees.Degree'),
        ),
    ]
