# -*- coding: utf-8 -*-
# Generated by Django 1.9.1.dev20151217143934 on 2015-12-18 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree_enrolments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degreeenrolment',
            options={'ordering': ('modified_at', 'created_at')},
        ),
        migrations.AlterModelOptions(
            name='degreemajorenrolment',
            options={'ordering': ('modified_at', 'created_at')},
        ),
        migrations.AlterModelOptions(
            name='degreeoriginalenrolment',
            options={'ordering': ('modified_at', 'created_at')},
        ),
        migrations.AlterModelOptions(
            name='degreetransfer',
            options={'ordering': ('modified_at', 'created_at')},
        ),
    ]
