# -*- coding: utf-8 -*-
# Generated by Django 1.9.1.dev20151217143934 on 2015-12-18 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_auto_20151210_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ('modified_at', 'created_at')},
        ),
        migrations.AlterModelOptions(
            name='assessmentresult',
            options={'ordering': ('modified_at', 'created_at')},
        ),
        migrations.AlterModelOptions(
            name='assessmenttype',
            options={'ordering': ('modified_at', 'created_at')},
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='_grade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_results', to='assessments.Assessment'),
        ),
    ]
