# -*- coding: utf-8 -*-
# Generated by Django 1.9.1.dev20151217143934 on 2015-12-18 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section_enrolments', '0002_auto_20151211_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsectionenrolment',
            options={'ordering': ('modified_at', 'created_at')},
        ),
    ]
