# -*- coding: utf-8 -*-
# Generated by Django 1.9.1.dev20151224150756 on 2016-01-11 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section_enrolments', '0003_auto_20151218_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionenrolmentlog',
            old_name='student_registration',
            new_name='period_registration',
        ),
        migrations.AlterUniqueTogether(
            name='sectionenrolmentlog',
            unique_together=set([('period_registration', 'section', 'enrolment_status')]),
        ),
    ]
