# -*- coding: utf-8 -*-
# Generated by Django 1.9.2.dev20160111111649 on 2016-01-12 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section_enrolments', '0005_sectionenrolment__grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionenrolment',
            name='_grade',
        ),
    ]
