# -*- coding: utf-8 -*-
# Generated by Django 1.9.2.dev20160111111649 on 2016-01-12 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_enrolments', '0006_remove_sectionenrolment__grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionenrolment',
            name='grade',
            field=models.FloatField(null=True),
        ),
    ]
