# -*- coding: utf-8 -*-
# Generated by Django 1.9.2.dev20160111111649 on 2016-01-12 01:40
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('section_enrolments', '0007_sectionenrolment_grade'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sectionenrolment',
            managers=[
                ('custom', django.db.models.manager.Manager()),
            ],
        ),
    ]
